CONFIG_ZMK_STUDIO_LOCKING=n
CONFIG_ZMK_POINTING=y
CONFIG_PAW3222=y
CONFIG_ZMK_BLE=y
CONFIG_BT=y
CONFIG_ZMK_SPLIT=y
CONFIG_SPI=y
CONFIG_BT_CENTRAL=n
CONFIG_BT_DEVICE_NAME="MyZMK"
CONFIG_BT_MAX_CONN=7
CONFIG_BT_MAX_PAIRED=8


